### ISSUE TITLE
iplist list broken after cidr blocks merge into a range

### ISSUE THREAD

**Issue by ospii** [FoobarOy/foomuuri#53]
0.25-1.foo9 with following iplist configuration:
```
iplist {
   @derp /etc/foomuuri/derp.iplist
}
```
After `foomuuri reload`
```
foomuuri iplist list derp
@derp                  1.1.64.0/18
```
Add another block to `/etc/foomuuri/derp.iplist`
```
1.1.64.0/18
1.1.128.0/17
```
`foomuuri iplist refresh derp` and running `foomuuri iplist list derp` burps following:
```
Traceback (most recent call last):
  File "/usr/sbin/foomuuri", line 3745, in <module>
    sys.exit(main())
  File "/usr/sbin/foomuuri", line 3740, in main
    return run_command()
  File "/usr/sbin/foomuuri", line 3722, in run_command
    return handler()
  File "/usr/sbin/foomuuri", line 3192, in command_iplist
    return command_iplist_list()
  File "/usr/sbin/foomuuri", line 3068, in command_iplist_list
    elem4 = [ipaddr for ipaddr, _dummy in iterate_set_elements(data4)]
  File "/usr/sbin/foomuuri", line 3068, in <listcomp>
    elem4 = [ipaddr for ipaddr, _dummy in iterate_set_elements(data4)]
  File "/usr/sbin/foomuuri", line 3008, in iterate_set_elements
    yield (f'{ipaddr["prefix"]["addr"]}/'
KeyError: 'prefix'
```
ruleset is ok, `foomuuri list|grep -A5 derp`
```
	set derp_4 {
		type ipv4_addr
		flags interval,timeout
		auto-merge
		elements = { 1.1.64.0-1.1.255.255 timeout 10d expires 9d23h59m38s295ms }
	}
```

**Comment by kimheino** [comment]
Fixed in above commit and in 0.25-2.foo9 (foobar-testing repo).
